#coding: utf-8

proc={
92: "tlswohi|s:smb|o:lqd|i:ptb", #пить", smb-некто, lqd-жидкость, ptb-часть тела
93: "tlswohi|s:smb|i:ptb", #кушать",
94: "tlswoi|s:smb", #кусать",
95: "tlswohi", #сосать",
96: "tlswhid", #плюнуть",
97: "tlswhid", #блевать",
98: "tlswhid", #дуть",
99: "tlswhi", #дышать",
100: "tlswh", #смеяться",
101: "tlswohi", #видеть",
102: "tlswohi", #слышать",
103: "tlswo", #вeдaть <small>(obsolete)</small>",
104: "tlswo", #мыслить",
105: "tlswoh", #чуять",
106: "tlswo", #страшиться",
107: "tlsw", #почивать <small>(poetic)</small>",
108: "tlsw", #жить",
109: "tlsw", #умирать",
110: "tlswohid", #забивать",
111: "tlswhi", #воевать",
112: "tlswhi", #охотиться",
113: "tlswohid", #ударить",
114: "tlswohi", #сечь <small>(arch.)</small>",
115: "tlswohi", #разделить",
116: "tlswohid", #пырнуть <small>(coll.)</small>",
117: "tlswohid", #чесать",
118: "tlswohid", #рыть",
119: "tlswhid", #плавать",
120: "tlswhid", #лететь",
121: "tlswhid", #идти",
122: "tswhid", #прийти",
123: "tlswi", #лежать",
124: "tlswi", #сидеть",
125: "tlswi", #стоять",
126: "tlswhid", #повернуть",
127: "tlswhd", #падать",
128: "tlswaohid", #дать",
129: "tlswoi", #держать",
130: "tlswoi", #стискивать",
131: "tlswohid", #тереть",
132: "tlswohi", #умывать",
133: "tlswohi", #вытирать",
134: "tlswohid", #тягать",
135: "tlswohid", #пихать",
136: "tlswohid", #швырять",
137: "tlswoid", #связывать",
138: "tlswohid", #шить",
139: "tlswohi", #считать",
140: "tlswaohi", #молвить",
141: "tlswaohi", #петь",
142: "tlswhi", #играть",
143: "tlswhid", #плавать",
144: "tlswhd", #течь",
145: "tlsw", #замёрзнуть",
146: "tlsw", #отекать",
169: "tlsw", #гореть",
}
