# -*- coding: utf-8 -*-

dictionary = {
1: "ego",
2: "tu|tū",
3: "is, ille (''that one'')",
4: "nos|nōs,  (''genitive pl'' : nostri|nostrī)",
5: "vos|vōs, (''genitive pl'' : vestri|vestrī)",
6: "ii|iī ''m'', eae ''f''",
7: "is, hic, iste ''m'', ista ''f''",
8: "iste (''near''), ille (''far''), is, hic",
9: "hic|hīc",
10: "ibi|ibī, illic",
11: "quis",
12: "quid",
13: "ubi|ubī, unde (''from where'')",
14: "quando|quandō",
15: "quam, quomodo|quōmodo",
16: "non|nōn",
17: "omnis, totus|tōtus",
18: "multus, ''pl'' multi|multī",
19: "aliqui|aliquī, aliquot    ",
20: "paucus    ",
21: "alter ''m'', altera ''f'', alius",
22: "unus|ūnus ''m'', una|ūna ''f''",
23: "duo ''m'', duae ''f''",
24: "tres|trēs",
25: "quattuor",
26: "quinque",
27: "magnus, grandis",
28: "longus",
29: "latus, amplus, largus",
30: "creber|crēber, grossus, spissus",
31: "gravis",
32: "parvus",
33: "curtus (''object''), brevis (''time'')",
34: "angustus, strictus (''tightened'')",
35: "macer, subtilis|subtīlis, tenuis",
36: "femina|fēmina, mulier",
37: "vir, homo|homō",
38: "homo|homō, humanum|hūmānum (''vulg.'')",
39: "infans|īnfāns, (''genitive sg'' : infantis), puer ",
40: "uxor, mulier, spōnsa ",
41: "maritus|marītus ",
42: "mater|māter, mamma (''childish'')",
43: "pater, tata (''childish'')",
44: "animal",
45: "piscis",
46: "avis, aucellus / avicellus (''diminutive'')",
47: "canis",
48: "pedis|pēdis, pediculus|pēdīculus (''diminutive'')",
49: "serpens|serpēns, (''genitive pl'' : serpentis), anguis, colubra|",
50: "vermis",
51: "arbor",
52: "silva, foresta (''vulg.''), boscus (''vulg.'') / (''dense wood, ",
53: "fustis, baculum ",
54: "fructus, frux|frūx",
55: "semen|sēmen",
56: "folium",
57: "radix|rādīx, (''genitive sg'' : radicis|rādīcis)        ",
58: "cortex ",
59: "flos|flōs, (''genitive sg'' : floris)        ",
60: "herba        ",
61: "funis|fūnis, chorda (''string'')    ",
62: "cutis, pellis (''animal hide / skin'')    ",
63: "caro|carō, (''genitive sg'' : carnis)    ",
64: "sanguis, cruor    ",
65: "os, (''genitive sg'' : ossis)    ",
66: "adeps, grassus / crassus  (''vulg.'')    ",
67: "ovum|ōvum    ",
68: "cornu|cornū    ",
69: "cauda    ",
70: "pluma|plūma, penna    ",
71: "capillus, coma, pilus    ",
72: "caput    ",
73: "auris, auricula (''diminutive'')    ",
74: "oculus    ",
75: "nasus|nāsus, naris|nāris (''nostrils, nose of animals'')    ",
76: "os|ōs, (''genitive sg'' : oris)    ",
77: "dens|dēns, (''genitive sg'' : dentis)    ",
78: "lingua    ",
79: "unguis, ungula (''nails / claws of an animal'')    ",
80: "pes|pēs, (''genitive sg'' : pedis), pediculus|pedīculus ",
81: "crus|crūs, perna (''thigh bone'')  ",
82: "genu|genū, geniculum (''diminutive'')      ",
83: "manus      ",
84: "ala|āla      ",
85: "venter, abdomen|abdōmen      ",
86: "intestīna|intestīna, chorda (''intestine'') ",
87: "collum, cervix|cervīx, nucha (''nape'') ",
88: "tergum, dorsum ",
89: "pectus, mamma, sinus      ",
90: "cor, (''genitive sg'' : cordis)      ",
91: "iecur, ficatum|fīcātum (''vulg.'')      ",
92: "bibere      ",
93: "edere, maducare|mandūcāre, comedere      ",
94: "mordere|mordēre      ",
95: "sugere|sūgere      ",
96: "sputare|spūtāre, spuere, exconspuere      ",
97: "vomere, vomitare|vomitāre      ",
98: "flare|flāre, sufflare|sufflāre      ",
99: "spirare|spīrāre, respirare|respīrāre      ",
100: "ridere|rīdēre      ",
101: "videre|vidēre      ",
102: "audire|audīre, intendere (''rare, meaning \"to understand\"'') ",
103: "scire|scīre, sapere (''to be wise'')      ",
104: "putare|putāre, cogitare|cōgitāre, pensare|pēnsāre (''to consider'') ",
105: "olere|olēre, sentire|sentīre (''to perceive a smell'')        ",
106: "timere|timēre        ",
107: "dormire|dormīre        ",
108: "vivere|vīvere        ",
109: "morior        ",
110: "venor|vēnor, captare|captāre (''to hunt down / capture'')      ",
111: "pugnare|pugnāre, luctor        ",
113: "pellere, battuere        ",
114: "secare|secāre, curtare|curtāre, taliare|taliāre (''vulg.'')    ",
115: "partior, dividere, findere, scindere        ",
116: "traicere, pungere          ",
117: "scalpere, rasicare|rasicāre, radere|rādere          ",
118: "fodere, cavare|cavāre (''to hollow out'')          ",
119: "natare|natāre        ",
120: "volare|volāre, exvolare|exvolāre (''vulg.'')        ",
121: "gradior, ambulare|ambulāre, vadere|vādere        ",
122: "venire|venīre        ",
123: "iacere|iacēre        ",
124: "sedere|sedēre        ",
125: "stare|stāre        ",
126: "vertere, gyrare|gȳrāre, tornare|tornāre, torquere|",
127: "cadere          ",
128: "dare, donare|dōnāre (''to give a present'')          ",
129: "tenere|tenēre          ",
130: "premere, comprimere, exprimere, stringere (''tighten'')",
131: "fricare|fricāre          ",
132: "lavare|lavāre    ",
133: "tergere|tergēre, exsucare|exsucāre, extergere|extergēre (''to ",
134: "trahere",
135: "pellere, urgere, pulsare|pulsāre, impulsare|impulsāre, ",
136: "iacere, iactare|iactāre, lanceare|lanceāre (''to throw a ",
137: "ligare|ligāre, stringere, aptare|aptāre (''to fasten'')",
138: "suere, consuere|cōnsuere    ",
139: "numerare|numerāre, computare|computāre (''count down / ",
140: "dicere|dīcere       ",
141: "canere, cantare|cantāre       ",
142: "ludere|lūdere, iocor       ",
143: "nare|nāre, natare|natāre       ",
144: "fluere, currere (''in the sense of \"running water\"'')       ",
145: "gelare|gelāre, glaciare|glaciāre (''to become ice'')       ",
146: "inflare|īnflāre ",
147: "sol|sōl ",
148: "luna|lūna ",
149: "stella|stēlla ",
150: "aqua ",
151: "pluvia ",
152: "flumen|flūmen, fluvius, rivus|rīvus (''creek'' / ''small river'')",
153: "lacus    ",
154: "mare    ",
155: "sal|sāl    ",
156: "lapis, petra    ",
157: "arena|arēna, sabulo|sabulō    ",
158: "pulvis ",
159: "terra (''also meaning \"land\"'')          ",
160: "nubes|nūbēs, nimbus (''large cloud'')          ",
161: "nebula, caligo|cālīgō ",
162: "caelum          ",
163: "ventus          ",
164: "nix, (''genitive sg'' : nivis)          ",
165: "glacies|glaciēs, gelu|gelū (''frost'' / ''water-ice'')          ",
166: "fumus|fūmus          ",
167: "ignis, focus (''fireplace'')          ",
168: "cinis, (''genitive sg'' : cineris)          ",
169: "ardere|ārdēre, cremare|cremāre    ",
170: "via, strata|strāta (''paved road'')    ",
171: "mons|mōns, (''genitive sg'' : montis)          ",
172: "ruber, vermiculus, russus (''rare'')          ",
173: "viridis          ",
174: "flavus|flāvus, galbinus (''yellowish'')          ",
175: "albus, candidus, blancus (''vulg.'')          ",
176: "niger, ater|āter, fuscus          ",
177: "nox|nōx, (''genitive sg'' : noctis)          ",
178: "dies|dīes, diurnum (''vulg.'' / ''diminutive'')          ",
179: "annus          ",
180: "calidus, caldus          ",
181: "frigidus|frīgidus          ",
182: "plenus|plēnus          ",
183: "novus          ",
184: "vetus, vetulus          ",
185: "bonus          ",
186: "malus          ",
187: "puter, putridus          ",
188: "sordidus          ",
189: "rectus          ",
190: "rotundus          ",
191: "acer|ācer, affiliatus, acūtus|acūtus          ",
192: "hebes, brutus          ",
193: "levis          ",
194: "umidus, madidus, udus|ūdus          ",
195: "siccus          ",
196: "rectus, correctus          ",
197: "propinquus, iuxta|iuxtā          ",
198: "procul, laxius, distāns, (''genitive sg.'' : distantis), ",
199: "dexter, directus (''straight'')          ",
200: "sinister          ",
201: "in, ad, ''ablative case''          ",
202: "in          ",
203: "cum, apud (''with accusative'')          ",
204: "et          ",
205: "si|sī          ",
206: "quia, quoniam          ",
207: "nomen|nōmen          ",
}
